repositoryUrl: https://github.com/Dynamsoft/label-recognition-docs/blob/master
repository: Dynamsoft/label-recognition-docs
docFullPath: https://www.dynamsoft.com/label-recognition
firstLevelUrl: /label-recognition
docHomePage: /label-recognition

parameters: /label-recognition/parameters/
enumerations: /label-recognition/parameters/enum/
parameters-reference: /label-recognition/parameters/reference/

programming: /label-recognition/programming/

c-cplusplus: /label-recognition/programming/c-cplusplus/
c-cplusplus-api-reference: /label-recognition/programming/c-cplusplus/api-reference/
c-functions: /label-recognition/programming/c-cplusplus/api-reference/c-functions/
cpp-methods: /label-recognition/programming/c-cplusplus/api-reference/c-label-recognition-class/
c-cplusplus-structs: /label-recognition/programming/c-cplusplus/api-reference/structs/

c-cplusplus-release-notes: /label-recognition/programming/c-cplusplus/release-notes/

android: /label-recognition/programming/android/
android-api: /label-recognition/programming/android/api-reference/
android-release-notes: /label-recognition/programming/android/release-notes/

dotnet: /label-recognition/programming/dotnet/
dotnet_api: /label-recognition/programming/dotnet/api-reference/
dotnet_release_notes: /label-recognition/programming/dotnet/release-notes/

objectivec-swift: /label-recognition/programming/objectivec-swift/
objectivec-swift-api: /label-recognition/programming/objectivec-swift/api-reference/
objectivec-swift-release-notes: /label-recognition/programming/objectivec-swift/release-notes/

java: /label-recognition/programming/java/
java-api: /label-recognition/programming/java/auxiliary-api/
java-release-notes: /label-recognition/programming/java/release-notes/

assets: /label-recognition/assets/
edit_icon: /label-recognition/assets/img-icon/edit-icon.png
smile_icon: /label-recognition/assets/img-icon/icon-smile.png
sad_icon: /label-recognition/assets/img-icon/icon-sad.png
dbr_icon: /label-recognition/assets/img-icon/icon-dbr.svg
dwt_icon: /label-recognition/assets/img-icon/icon-dwt.svg
dnt_icon: /label-recognition/assets/img-icon/icon-dnt.svg

baseurl: "/label-recognition"
plugins:
  - jemoji

